name: CI

on:
  push:
    branches: [master]
  schedule:
    - cron: "30 17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install nodejs
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: "16.x"
      - name: install
        run: |
          pnpm install
          pnpm run build
      - name: usegit
        run: |
          git config --global user.email "zyj17715640603@gmail.com"
          git remote set-url origin https://github.com/Jack-Zhang-1314/player.git
          git add .
          git commit -m "build docs"
          git push origin master
